= Prepare Cluster
include::_attributes.adoc[]
:username: user1
:password: openshift

Everything we do in this section requires that you have fulfilled the xref:01-setup.adoc#prerequisite[prerequisites] section and you're logged in your OpenShift cluster.

[WARNING]
====
*EVEN* if you have two clusters and want to run the multicluster section... so... *log in the main one now* [.underline]#not in the secondary#.
====

So if not already logged in, please do it now.

[source,sh]
----
oc login -u USER -p PASS --server=https://api.cluster.example.com:6443
----

[#install-operators]
== Installing ArgoCD and Pipelines using the operators

In order to run this guide we're going to need several components, more prominently:

- *ArgoCD*, the GitOps engine supported by Red Hat through the *OpenShift GitOps operator*
- *Tekton*, the _de facto_ kubernetes native CICD pipelines system supported by Red Hat through the *OpenShift Pipelines operator*

Install *ArgoCD* (with OpenShift OAuth configured) and *Tekton*:

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
until kubectl apply -k util/bootstrap/; do sleep 2; done
----

