= Prepare ArgoCD
include::_attributes.adoc[]

*ArgoCD* is the *GitOps* engine *OpenShift GitOps* rely on it should have been installed previously in xref:02-prepare-cluster.adoc#install-operators[Install Operators].


[#checking-argocd]
== Checking ArgoCD

include::partial$argocd-tests.adoc[]

[#log-in-argocd]
== Log in ArgoCD with CLI

Well *ArgoCD* is healthy now let's see if the *CLI* works correctly by trying to log in with it (you should have installed as stated in xref:01-setup.adoc#prerequisite[Prerequisites] section).

[IMPORTANT]
====
You'll be redirected to OpenShift Web Console to enter your credentials:

- USERNAME: {username}
- PASSWORD: {password}
====

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
argocd login {argocd-server} --insecure --sso
----

After being successfully logged in, you should be redirected to localhost:8085 with a message of successful authentication and in the terminal output you should see something similar to this.

[.console-output]
[source,bash, subs="+macros,+attributes"]
----
Opening browser for authentication
Performing authorization_code flow login: https://{argocd-server}/api/dex/auth?access_type=offline&client_id=argo-cd-cli&code_challenge=VVX5Feb1ySsRQAUNfvSrolTt8yak2HKjUZ-YjuQgItI&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups+offline_access&state=zsQHLaywsv
Authentication successful
'{username}' logged in successfully
Context '{argocd-server}' updated
----

[#register-repositories]
== Register Repositories

In this guide we cover the case of a protected git repository that needs to be interacted with from a system and you don't want your personal password to be exposed that’s why you have created a *Personal Access Token*.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
argocd --insecure repo add https://{gitea-host}/{username}/gramola.git --username {username} --password ${GIT_PAT} --upsert
----

Run this command to list the registered repositories.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
argocd --insecure repo list
----

This is a typical response.

[.console-output]
[source,bash, subs="+macros,+attributes"]
----
TYPE  NAME  REPO                                                                                                           INSECURE  OCI    LFS    CREDS  STATUS      MESSAGE
git         https://{gitea-host}/user1/gramola.git          false     false  false  true   Successful  
----

[#register-additional-clusters]
== Register Additional Clusters

First make sure there is a context with proper credentials, in order to achieve this please log in the additional cluster.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export API_SERVER=localhost:8443
oc login ${API_SERVER} --username=myuser --password=mypass
----

CAUTION: *CLUSTER_NAME* is a name you choose for your cluster, *API_SERVER* is the *host and port* of the cluster API server *BUT without http(s)*.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export CLUSTER_NAME=aws-managed1
./util/argocd-register-cluster.sh ${CLUSTER_NAME} ${API_SERVER}
----

Check if your cluster has been added correctly.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
argocd --insecure cluster list
----

[#project-definitions]
== Project definitions

In ArgoCD you can constrain which repositories and destinations can be linked with the definition of an application, in our case we are not constraining but we still have created project definitions to be prepared for future needs. 

Run this command to see the list of project definitions.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
argocd --insecure proj list
----

This is the expected result, one project definition for development and another one for testing.

[.console-output]
[source,bash, subs="+macros,+attributes"]
----
NAME                  DESCRIPTION           DESTINATIONS  SOURCES  CLUSTER-RESOURCE-WHITELIST  NAMESPACE-RESOURCE-BLACKLIST  SIGNATURE-KEYS  ORPHANED-RESOURCES
default                                     *,*           *        */*                         <none>                        <none>          disabled
gramola-project-dev   Gramola Project Dev   *,*           *        */*                         <none>                        <none>          disabled
gramola-project-test  Gramola Project Test  *,*           *        */*                         <none>                        <none>          disabled
----