= Deploy Gramola With GitOps
include::_attributes.adoc[]
:username: user1
:password: openshift
:namespace-suffix: -{username}
:root-apps-namespace: openshift-gitops

[#create-root-apps]
== Create Root Apps

ArgoCD uses a powerful abstraction of what an application is from the point of view of deployment. In an ArgoCD application we define where to look for the descriptors we want to create (*spec->source*) and maintain in Kubernetes and also how and where we want them (*spec->destination*). More over, because we can store Application objects also in git repository we could chain a set of applications with a parent application... hence we can nest application and call "*Root Application*" to the top parent of a set of elements including Applications.

The next command creates a Root Application called *gramola-root-app* that points to our configuration repository at *${BASE_REPO_URL}* and folder *argocd/root-apps*.

*BASE_REPO_URL* points to your migrated configuration repo.

NOTE: https://argoproj.github.io/argo-cd/user-guide/helm/

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export BASE_REPO_URL=https://${GITEA_HOST}/{username}/gramola

cat <<EOF | kubectl apply -n {root-apps-namespace} -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gramola-root-app-{namespace-suffix}
  namespace: {root-apps-namespace}
  labels:
    argocd-root-app: "true"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {root-apps-namespace}
    name: in-cluster
  project: default
  syncPolicy:
    automated: {}
  source:
    helm:
      parameters:
        - name: baseRepoUrl
          value: ${BASE_REPO_URL}
        - name: namespaceSuffix
          value: "{namespace-suffix}"
    path: argocd/root-apps
    repoURL: ${BASE_REPO_URL}
    targetRevision: HEAD
EOF
----

If an additional cluster has been set up

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -n {root-apps-namespace} -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gramola-root-app-cloud-{namespace-suffix}
  namespace: {root-apps-namespace}
  labels:
    argocd-root-app: "true"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {root-apps-namespace}
    name: in-cluster
  project: default
  syncPolicy:
    automated: {}
  source:
    helm:
      parameters:
        - name: baseRepoUrl
          value: ${BASE_REPO_URL}
        - name: destinationName
          value: ${CLUSTER_NAME}
        - name: namespaceSuffix
          value: "{namespace-suffix}"
    path: argocd/root-apps-cloud
    repoURL: ${BASE_REPO_URL}
    targetRevision: HEAD
EOF
----

