= Deploy Gramola With GitOps
include::_attributes.adoc[]

[#create-root-app]
== Create Root App

ArgoCD uses a powerful abstraction of what an application is from the point of view of deployment. In an ArgoCD application we define where to look for the descriptors we want to create (*spec->source*) and maintain in Kubernetes and also how and where we want them (*spec->destination*). More over, because we can store Application objects also in git repository we could chain a set of applications with a parent application... hence we can nest application and call "*Root Application*" to the top parent of a set of elements including Applications.

The next command creates a Root Application called *gramola-root-app* that points to our configuration repository https://{gitea-host}/{username}/gramola[^] and folder *argocd/root-apps*.

NOTE: Go link:https://argoproj.github.io/argo-cd/user-guide/helm/[here^] to learn more about the ArgoCD helm plugin.

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export USERNAME="{namespace-suffix}"
cat <<EOF | kubectl apply -n {root-apps-namespace} -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gramola-root-app-$\{USERNAME}
  namespace: {root-apps-namespace}
  labels:
    argocd-root-app: "true"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {root-apps-namespace}
    name: in-cluster
  project: default
  syncPolicy:
    automated: {}
  source:
    helm:
      parameters:
        - name: baseRepoUrl
          value: https://{gitea-host}/{username}/gramola
        - name: namespaceSuffix
          value: "-$\{USERNAME}"
        - name: username
          value: "{username}"
    path: argocd/root-apps
    repoURL: https://{gitea-host}/{username}/gramola
    targetRevision: HEAD
EOF
----

You should see something like.

[.console-output]
[source,bash, subs="+macros,+attributes"]
----
application.argoproj.io/gramola-root-app-user1 created
----

[#create-additional-root-app]
== Create Additional Root App TODO!!!

If an additional cluster has been set up...

[.console-input]
[source,bash, subs="+macros,+attributes"]
----
export USERNAME="{namespace-suffix}"
cat <<EOF | kubectl apply -n {root-apps-namespace} -f -
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gramola-root-app-cloud-$\{USERNAME}
  namespace: {root-apps-namespace}
  labels:
    argocd-root-app: "true"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {root-apps-namespace}
    name: in-cluster
  project: default
  syncPolicy:
    automated: {}
  source:
    helm:
      parameters:
        - name: baseRepoUrl
          value: https://{gitea-host}/{username}/gramola
        - name: destinationName
          value: ${CLUSTER_NAME}
        - name: namespaceSuffix
          value: "-$\{USERNAME}"
        - name: username
          value: "{username}"
    path: argocd/root-apps-cloud
    repoURL: https://{gitea-host}/{username}/gramola
    targetRevision: HEAD
EOF
----

Similarly if you created the root app for the additional cluster you should see...

[.console-output]
[source,bash, subs="+macros,+attributes"]
----
application.argoproj.io/gramola-root-app-cloud-user1 created
----